export const opportunityFieldOptions = {
  domain: [
    'Banking',
    'Education',
    'Energy',
    'Financial Services',
    'Healthcare',
    'Insurance',
    'Internal Platforms',
    'Legacy Platforms',
    'Logistics',
    'Media',
    'Payments',
    'Public Sector',
    'Retail',
    'Telecommunications',
    'Travel',
  ],
  country: [
    'Australia',
    'Egypt',
    'India',
    'Jordan',
    'Malaysia',
    'Saudi Arabia',
    'Singapore',
    'UAE',
    'Vietnam',
  ],
  region: [
    'APAC',
    'India',
    'MENA',
  ],
  city: [
    'Abu Dhabi',
    'Amman',
    'Bengaluru',
    'Brisbane',
    'Cairo',
    'Canberra',
    'Chennai',
    'Da Nang',
    'Delhi',
    'Dubai',
    'Hanoi',
    'Ho Chi Minh City',
    'Hyderabad',
    'Jeddah',
    'Kuala Lumpur',
    'Melbourne',
    'Mumbai',
    'Penang',
    'Perth',
    'Pune',
    'Riyadh',
    'Singapore',
    'Sydney',
  ],
  timezonePreference: [
    'AEST/AEDT',
    'AST',
    'EET',
    'GST',
    'ICT',
    'IST',
    'MYT',
    'SGT',
  ],
} as const
export const opportunityLocationHierarchy = {
  APAC: {
    Australia: ['Brisbane', 'Canberra', 'Melbourne', 'Perth', 'Sydney'],
    Malaysia: ['Kuala Lumpur', 'Penang'],
    Singapore: ['Singapore'],
    Vietnam: ['Da Nang', 'Hanoi', 'Ho Chi Minh City'],
  },
  India: {
    India: ['Bengaluru', 'Chennai', 'Delhi', 'Hyderabad', 'Mumbai', 'Pune'],
  },
  MENA: {
    Egypt: ['Cairo'],
    Jordan: ['Amman'],
    'Saudi Arabia': ['Jeddah', 'Riyadh'],
    UAE: ['Abu Dhabi', 'Dubai'],
  },
} as const
