import { Loader2 } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { useLocation, useNavigate, useParams } from 'react-router-dom'
import type { EwaRecommendationSelectionPayload } from '../api/ewaApi'
import { recommendationApi } from '../api/recommendationApi'
import AiExplanationCta from '../components/recommendation/AiExplanationCta'
import AiGenerationOverlay from '../components/recommendation/AiGenerationOverlay'
import EmptyRecommendationState from '../components/recommendation/EmptyRecommendationState'
import OpportunityDetailsCard from '../components/recommendation/OpportunityDetailsCard'
import PersonDetailDrawer from '../components/recommendation/PersonDetailDrawer'
import RecommendationHeader from '../components/recommendation/RecommendationHeader'
import TeamComparisonTable from '../components/recommendation/TeamComparisonTable'
import TeamOptionCard from '../components/recommendation/TeamOptionCard'
import {
  findMemberExplanation,
  findOptionExplanation,
  firstOptionType,
  normalizedList,
  optionConfig,
  optionMatchScore,
  sortOptions,
  toNumber,
} from '../components/recommendation/recommendationDisplayUtils.ts'
import './RecommandationPage.css'
import type { Opportunity } from '../types/Opportunity'
import type { OpportunityRole } from '../types/OpportunityRoles'
import type {
  RecommendationExplanationResponse,
  RecommendationOption,
  RecommendationRun,
  RecommendationRunMember,
} from '../types/Recommendation'

type SelectedMember = {
  option: RecommendationOption
  member: RecommendationRunMember
}

type MemberWithOverlayReference = RecommendationRunMember & {
  opportunityOverlayId?: string
  overlayId?: string
}

type RecommendationRouteState = {
  generateRecommendations?: boolean
}

const defaultOpportunityId = 'OPP-001'

function RecommendationPage() {
  const { id: routeOpportunityId } = useParams<{ id: string }>()
  const location = useLocation()
  const navigate = useNavigate()
  const opportunityId = normalizeOpportunityId(routeOpportunityId)
  const comparisonRef = useRef<HTMLDivElement | null>(null)
  const autoGenerateStartedRef = useRef(false)
  const [opportunity, setOpportunity] = useState<Opportunity | null>(null)
  const [roles, setRoles] = useState<OpportunityRole[]>([])
  const [recommendationRun, setRecommendationRun] =
    useState<RecommendationRun | null>(null)
  const [explanation, setExplanation] =
    useState<RecommendationExplanationResponse | null>(null)
  const [selectedOptionType, setSelectedOptionType] = useState<string | null>(
    null,
  )
  const [selectedMember, setSelectedMember] = useState<SelectedMember | null>(
    null,
  )
  const [isLoading, setIsLoading] = useState(true)
  const [isGenerating, setIsGenerating] = useState(false)
  const [isExplaining, setIsExplaining] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [notice, setNotice] = useState<string | null>(null)
  const [ewaMessage, setEwaMessage] = useState<string | null>(null)
  const routeState = location.state as RecommendationRouteState | null
  const shouldGenerateRecommendationsOnLoad = Boolean(
    routeState?.generateRecommendations,
  )

  useEffect(() => {
    let active = true

    async function loadPage() {
      if (routeOpportunityId !== opportunityId) {
        navigate(`/opportunities/${opportunityId}/recommendations`, {
          replace: true,
        })
      }

      setIsLoading(true)
      setError(null)
      setNotice(null)
      setExplanation(null)

      try {
        let latestRun: RecommendationRun | null = null

        if (
          shouldGenerateRecommendationsOnLoad &&
          !autoGenerateStartedRef.current
        ) {
          autoGenerateStartedRef.current = true
          setIsGenerating(true)
          latestRun =
            await recommendationApi.generateRecommendationRun(opportunityId)
          if (active) {
            setNotice('Recommendation run generated by the backend scoring engine.')
            navigate(`/opportunities/${encodeURIComponent(opportunityId)}/recommendations`, {
              replace: true,
              state: null,
            })
          }
        } else {
          latestRun =
            await recommendationApi.getLatestRecommendationRun(opportunityId)
        }

        if (!active) {
          return
        }

        setRecommendationRun(latestRun)
        setSelectedOptionType(firstOptionType(latestRun))

        const [loadedOpportunity, loadedRoles] = await Promise.allSettled([
          recommendationApi.getOpportunity(opportunityId),
          recommendationApi.getOpportunityRoles(opportunityId),
        ])

        if (!active) {
          return
        }

        setOpportunity(
          loadedOpportunity.status === 'fulfilled'
            ? loadedOpportunity.value
            : null,
        )
        setRoles(loadedRoles.status === 'fulfilled' ? loadedRoles.value : [])

        if (latestRun?.recommendationRunId) {
          const cachedExplanation =
            await recommendationApi.getRecommendationExplanation(
              latestRun.recommendationRunId,
            )
          if (active && cachedExplanation?.explanations) {
            setExplanation(cachedExplanation)
          }
        }
      } catch (loadError) {
        if (active) {
          setError(errorMessage(loadError))
        }
      } finally {
        if (active) {
          setIsLoading(false)
          setIsGenerating(false)
        }
      }
    }

    loadPage()

    return () => {
      active = false
    }
  }, [
    navigate,
    opportunityId,
    routeOpportunityId,
    shouldGenerateRecommendationsOnLoad,
  ])

  const options = useMemo(
    () => sortOptions(recommendationRun?.options ?? []),
    [recommendationRun],
  )

  const selectedOption = useMemo(
    () =>
      options.find((option) => option.optionType === selectedOptionType) ??
      options[0] ??
      null,
    [options, selectedOptionType],
  )

  const hasExplanation = Boolean(explanation?.explanations)
  const roleCount = roles.length
  const totalFte = roles.reduce(
    (sum, role) => sum + (toNumber(role.fteRequired) ?? 0),
    0,
  )

  async function handleGenerateRecommendations() {
    if (!opportunityId) {
      return
    }

    setIsGenerating(true)
    setError(null)
    setNotice(null)
    setExplanation(null)
    setSelectedMember(null)

    try {
      const run = await recommendationApi.generateRecommendationRun(
        opportunityId,
      )
      setRecommendationRun(run)
      setSelectedOptionType(firstOptionType(run))
      setNotice('Recommendation run generated by the backend scoring engine.')
    } catch (generateError) {
      setError(errorMessage(generateError))
    } finally {
      setIsGenerating(false)
    }
  }

  async function handleGenerateExplanation() {
    if (!recommendationRun?.recommendationRunId) {
      return
    }

    setIsExplaining(true)
    setNotice(null)
    setError(null)

    try {
      const response = await recommendationApi.generateRecommendationExplanation(
        recommendationRun.recommendationRunId,
      )
      setExplanation(response)
      setRecommendationRun((current) =>
        current
          ? {
              ...current,
              explanationStatus:
                response.explanationStatus ?? 'AI_EXPLANATION_GENERATED',
            }
          : current,
      )
      setNotice(
        response.fallbackUsed
          ? 'AI fallback explanations were saved.'
          : response.cached
            ? 'Cached AI explanation loaded from MongoDB.'
            : 'AI explanation generated and saved.',
      )
    } catch (explanationError) {
      setError(errorMessage(explanationError))
    } finally {
      setIsExplaining(false)
    }
  }

  function handlePrepareEwaPack() {
    if (!recommendationRun?.recommendationRunId || !selectedOption) {
      setEwaMessage('Select a recommendation option before preparing EWA.')
      return
    }

    const selectedOptionIndex = Math.max(
      options.findIndex(
        (option) => option.optionType === selectedOption.optionType,
      ),
      0,
    )
    const payload = buildEwaSelectionPayload(
      recommendationRun.opportunityId ?? opportunityId,
      selectedOption,
      selectedOptionIndex,
    )

    if (!payload.selectedCandidates.length) {
      setEwaMessage('Selected option has no candidate data for EWA.')
      return
    }

    setEwaMessage(null)
    navigate('/ewa', { state: payload })
  }

  if (isLoading) {
    return (
      <section className="recommendation-page">
        <div className="recommendation-loading">
          <Loader2 className="spin" size={22} />
          <span>Loading recommendation workspace...</span>
        </div>
      </section>
    )
  }

  return (
    <section className="recommendation-page">
      <RecommendationHeader
        comparisonRef={comparisonRef}
        onPrepareEwaPack={handlePrepareEwaPack}
        recommendationRun={recommendationRun}
        selectedOption={selectedOption}
      />

      {isExplaining ? <AiGenerationOverlay /> : null}

      {error ? <div className="message error-message">{error}</div> : null}
      {notice ? <div className="message success-message">{notice}</div> : null}
      {ewaMessage ? (
        <div className="message info-message">{ewaMessage}</div>
      ) : null}

      <OpportunityDetailsCard
        opportunity={opportunity}
        recommendationRun={recommendationRun}
        roleCount={roleCount}
        roles={roles}
        totalFte={totalFte}
      />

      {recommendationRun && !hasExplanation ? (
        <AiExplanationCta
          disabled={isExplaining}
          onGenerate={handleGenerateExplanation}
        />
      ) : null}

      {!recommendationRun ? (
        <EmptyRecommendationState
          isGenerating={isGenerating}
          onGenerate={handleGenerateRecommendations}
          opportunityName={opportunity?.opportunityName}
        />
      ) : (
        <>
          <div className="option-grid">
            {options.map((option, index) => (
              <TeamOptionCard
                explanation={findOptionExplanation(explanation, option)}
                isSelected={selectedOption?.optionType === option.optionType}
                key={option.optionType ?? index}
                onSelect={() =>
                  setSelectedOptionType(option.optionType ?? null)
                }
                onSelectMember={(member) => setSelectedMember({ option, member })}
                option={option}
                optionIndex={index}
              />
            ))}
          </div>

          <TeamComparisonTable
            explanation={explanation}
            isExplaining={isExplaining}
            onGenerateExplanation={handleGenerateExplanation}
            options={options}
            refNode={comparisonRef}
          />
        </>
      )}

      {selectedMember ? (
        <PersonDetailDrawer
          explanation={findMemberExplanation(
            explanation,
            selectedMember.option,
            selectedMember.member,
          )}
          isExplaining={isExplaining}
          member={selectedMember.member}
          onClose={() => setSelectedMember(null)}
          onGenerateExplanation={handleGenerateExplanation}
          option={selectedMember.option}
        />
      ) : null}
    </section>
  )
}

function normalizeOpportunityId(value?: string) {
  if (!value) {
    return defaultOpportunityId
  }

  const decoded = safeDecode(value).trim()
  if (
    !decoded ||
    decoded === 'sample' ||
    decoded === ':opportunityId' ||
    decoded.includes('{') ||
    decoded.includes('}')
  ) {
    return defaultOpportunityId
  }

  return decoded
}

function safeDecode(value: string) {
  try {
    return decodeURIComponent(value)
  } catch {
    return value
  }
}

function buildEwaSelectionPayload(
  opportunityId: string,
  option: RecommendationOption,
  optionIndex: number,
): EwaRecommendationSelectionPayload {
  const config = optionConfig(option, optionIndex)

  return {
    opportunityId,
    selectedOption: {
      optionName: config.label.replace(`${config.shortLabel}: `, ''),
      matchScore: optionMatchScore(option) ?? undefined,
      confidence: toNumber(option.confidenceScore) ?? undefined,
      riskLevel: option.riskLevel,
      teamSize: option.selectedMemberCount ?? option.members?.length ?? 0,
      locationFitScore: toNumber(option.locationFitScore) ?? undefined,
      locationFit: normalizedList(option.locationFit),
      skillCoverageScore: toNumber(option.skillCoverageScore) ?? undefined,
      matchedRequiredSkills: normalizedList(option.matchedRequiredSkills),
      missingRequiredSkills: normalizedList(option.missingRequiredSkills),
      matchedDesiredSkills: normalizedList(option.matchedDesiredSkills),
      missingDesiredSkills: normalizedList(option.missingDesiredSkills),
    },
    selectedCandidates: (option.members ?? [])
      .filter((member) => member.opportunityRoleId && member.employeeId)
      .map((member) => {
        const memberWithOverlay = member as MemberWithOverlayReference

        return {
          opportunityOverlayId:
            memberWithOverlay.opportunityOverlayId ??
            memberWithOverlay.overlayId,
          opportunityId,
          opportunityRoleId: member.opportunityRoleId as string,
          employeeId: member.employeeId as string,
          matchScore: toNumber(member.matchScore) ?? undefined,
          capabilityFitScore: toNumber(member.capabilityFitScore) ?? undefined,
          availabilityFitScore: toNumber(member.availabilityFitScore) ?? undefined,
          overallStaffingScore: toNumber(member.overallStaffingScore) ?? undefined,
          availableFTEAtStart: toNumber(member.availableFteAtStart) ?? undefined,
          fteGap: toNumber(member.fteGap) ?? undefined,
          locationFitScore: toNumber(member.locationFitScore) ?? undefined,
          locationFit: normalizedList(member.locationFit),
          skillCoverageScore: toNumber(member.skillCoverageScore) ?? undefined,
          matchedRequiredSkills: normalizedList(member.matchedRequiredSkills),
          missingRequiredSkills: normalizedList(member.missingRequiredSkills),
          matchedDesiredSkills: normalizedList(member.matchedDesiredSkills),
          missingDesiredSkills: normalizedList(member.missingDesiredSkills),
          requiredSkillsMatched: normalizedList(member.matchedRequiredSkills).length,
          requiredSkillsTotal:
            normalizedList(member.matchedRequiredSkills).length +
            normalizedList(member.missingRequiredSkills).length,
          desiredSkillsMatched: normalizedList(member.matchedDesiredSkills).length,
          desiredSkillsTotal:
            normalizedList(member.matchedDesiredSkills).length +
            normalizedList(member.missingDesiredSkills).length,
        }
      }),
  }
}

function errorMessage(error: unknown) {
  if (error instanceof Error) {
    return error.message
  }
  return 'Unexpected request failure.'
}

export default RecommendationPage
