spring.application.name=backend

spring.mongodb.uri=mongodb://localhost:27017/ai-workforce-planner

app.import.employee-dataset=classpath:data/workforce-dataset.xlsx
app.import.employee-dataset-on-startup=true